[tool.bumpversion]
current_version = "0.1.8"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "mtgwebapp.py"
search = 'MTG_APP_VERSION = "{current_version}"'
replace = 'MTG_APP_VERSION = "{new_version}"'

[[tool.bumpversion.files]]
filename = "mylibs/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'